spring.application.name=sq-ch12-ex3

custom.datasource.url=jdbc:postgresql://localhost:5432/postgres
custom.datasource.username=postgres
custom.datasource.password=postgres
spring.sql.init.mode=always

